### ISSUE TITLE
Allow testing of models constructed via Model.init

### ISSUE THREAD

**Issue by rv4Flyver** [davesag/sequelize-test-helpers#115]
When my modales are defined using Sequelize.Model.init(attributes, options) a TypeError is thrown: 
```
......./node_modules/sequelize/lib/model.js:926
    options = Utils.merge(_.cloneDeep(globalOptions.define), options);
                                                    ^

TypeError: Cannot read property 'define' of undefined
    at Function.init (......./node_modules/sequelize/lib/model.js:926:53)
    at module.exports (......./server/models/TAGS.js:7:7)
    at Suite.describe (......./server/test/unit/tags.test.js:11:23)
    at Object.create (......./node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (......./node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Object.<anonymous> (......./server/test/unit/tags.test.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at ......./node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (......./node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (......./node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (......./node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

"chai": "^4.1.2",
"sequelize": "^5.8.9"
"mocha": "^5.2.0",
"sequelize-test-helpers": "^1.1.2"

**Comment by davesag** [comment]
This appears to be an issue within `sequelize` and not `sequelize-test-helpers`.

If you could create a simple repo that shows the issue I would be happy to take a look.

**Comment by gabrieloczkowski** [comment]
@davesag  I have the same issue:
`
class UserModel extends Sequelize.Model {}
UserModel.init(this.properties, this.options);
`
`this.options` contains `sequelize` from `sequelize-test-helpers`.
When using standard sequelize library it's working correctly.

**Comment by davesag** [comment]
@gabrieloczkowski can you point me at a repo?

**Comment by gabrieloczkowski** [comment]
@davesag Sorry I can't because it's private project. I provided all necessary information, there is nothing more. `sequelize` from `sequelize-test-helpers` have only `define` property but when using `init` it requires `globalOptions` property.

**Comment by davesag** [comment]
@gabrieloczkowski what confuses me is why you are calling UserModel.init within the test

**Comment by gabrieloczkowski** [comment]
@davesag It's not inside tests. I'm using factory class with dependency injection pattern (sequelize dependency) which produces UserModel. I'm using only UserModel in tests and I wanted to use sequelize from sequelize-test-helpers instead my own sequelize module to have independent tests from other modules.

**Comment by davesag** [comment]
@gabrieloczkowski Okay. That method of building Sequelize models is not familiar to me. I'd need to go do some reading. I'm much more used to creating models as per the way described in the readme, namely

```js
const model = (sequelize, DataTypes) => {
  const User = sequelize.define(
    'User',
    {
       // field definitions
    },
   {
     // indexes etc
   }
  )

  // User.associate etc
  return User
}

module.exports = model
```

that is then in turn loaded via `sequelize.import` in `src/models/index.js`

You still get the benefits of dependency injection.

I've never seen people do it the way you are doing it but yes, looking at https://sequelize.org/master/manual/getting-started.html I see that's a thing.

I'll take a closer look at this over the weekend.

Cheers

D

**Comment by gabrieloczkowski** [comment]
@davesag The way how I doing it don't need to use `sequelize.import`. Everything happening in one file with that model, much cleaner way in my opinion.

**Comment by davesag** [comment]
@gabrieloczkowski fair enough. I'll look into supporting it in a forthcoming release

**Comment by gabrieloczkowski** [comment]
```
class SomeModelFactory {
  constructor(sequelize) {
    this.sequelize = sequelize;
  }
  get class () {
    class SomeModel extends Sequelize.Model {}
    SomeModel.init(this.properties, this.options);
    return SomeModel;
  }
  get options () {
    <options like sequelize, modelName etc.>
  }
  get properties () {
    <properties>
  }
}
```

**Comment by davesag** [comment]
@gabrieloczkowski okay I am looking at this now.  I have created a simple User model as follows, following your pattern

`src/models/User.js`

```js
const { Model, DataTypes } = require('sequelize')

class Factory {
  constructor(sequelize) {
    this.sequelize = sequelize;
  }
  get user() {
    class User extends Model {}
    User.init(this.properties, this.options);
    return User;
  }
  get options () {
    return {
      sequelize: this.sequelize,
      modelName: 'User'
    }
  }
  get properties () {
    return {
      firstName: DataTypes.STRING,
      lastName: DataTypes.STRING
    }
  }
}

module.exports = Factory
```

which I then invoke as follows

`src/server.js`

```js
const Sequelize = require('sequelize')
const { makeInitialiser, configure } = require('sequelize-pg-utilities')
const config = require('config/db_config.json')
const UserFactory = require('./models/User')

const { name, user, password, options } = configure(config)

const sequelize = new Sequelize(name, user, password, options)

const start = async () => {
  const dbInit = makeInitialiser(config)

  try {
    const result = await dbInit()
    console.log(result.message)

    const userFactory = new UserFactory(sequelize)
    const User = userFactory.User
    // never use User here, it's just to create it.
    // models can be retrieved from sequelize after creation
    sequelize.sync({ force: true })

    return sequelize
  } catch (err) {
    console.error('Could not start the server', err)
    process.exit(1)
  }
}

module.exports = { start }
```

It that a fair approximation?

Honestly that's a lot of code to create a simple User.  You could simplify this to

`src/models/User.js`

```js
const { Model, DataTypes } = require('sequelize')

const factory = sequelize => {
  class User extends Model {}
  User.init({
    firstName: DataTypes.STRING,
    lastName: DataTypes.STRING
  }, { sequelize, modelName: 'User' })
  return User
}

module.exports = factory
```

then

`src/server.js`

```js
const Sequelize = require('sequelize')
const { makeInitialiser, configure } = require('sequelize-pg-utilities')
const config = require('config/db_config.json')
const User = require('src/models/User')

const { name, user, password, options } = configure(config)

const sequelize = new Sequelize(name, user, password, options)

const start = async () => {
  const dbInit = makeInitialiser(config)

  try {
    const result = await dbInit()
    console.log(result.message)

    User(sequelize) // makes the user model accessible from sequelize

    sequelize.sync({ force: true })

    return sequelize
  } catch (err) /* istanbul ignore next */ {
    console.error('Could not start the server', err)
    process.exit(1)
  }
}

module.exports = { start }
```

But I guess that's besides the point: the two ways are functionally equivalent, its just always better to avoid making needless amounts of classes when using javascript.

I'm going to work out how to unit test this kind of model now, so please bear with me.

**Comment by davesag** [comment]
Okay so given a user model like this

```js
const { Model, DataTypes } = require('sequelize')

const factory = sequelize => {
  class User extends Model {}
  User.init({
    firstName: DataTypes.STRING,
    lastName: DataTypes.STRING
  }, { sequelize, modelName: 'User' })
  return User
}

module.exports = factory
```

I was able to test it as follows

```js
const { expect } = require('chai')
const { spy } = require('sinon')
const proxyquire = require('proxyquire')
const { sequelize, dataTypes: DataTypes } = require('sequelize-test-helpers')

describe('src/models/User', () => {
  class Model {}
  Model.init = spy()

  const mockSq = {
    Model,
    DataTypes
  }

  const UserFactory = proxyquire('src/models/User', {
    sequelize: mockSq
  })

  let User

  before(() => {
    User = UserFactory(sequelize)
  })

  it('called User.init with the correct parameters', () => {
    expect(User.init).to.have.been.calledWith({
      firstName: DataTypes.STRING,
      lastName: DataTypes.STRING
    }, {
      sequelize,
      modelName: 'User'
    })
  })
})
```

```sh
> NODE_PATH=. NODE_ENV=test nyc mocha ./test/unit/ --require ./test/unitTestHelper.js --recursive



  src/models/User
    ✓ called User.init with the correct parameters


  1 passing (6ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 User.js  |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

You could use the same approach to test your class based factory.  The key is to use proxyquire to stub out `Sequelize.Model` and then test that what's going into `Model.init` is what you expect.

Let me know if that helps you.

**Comment by davesag** [comment]
Here's a zipped up version.

[davesag-sq-class-example-1.0.0.tgz.zip](https://github.com/davesag/sequelize-test-helpers/files/3853869/davesag-sq-class-example-1.0.0.tgz.zip)

**Comment by davesag** [comment]
I have release a new version `1.2.0` that now supports testing of a model created by extending `Sequelize.Model` and invoking its `init` function.

See #117 for the PR and see the updated README

Thanks for your suggestions.

See this working example for how it's used.

[davesag-sq-class-example-1.0.1.tgz.zip](https://github.com/davesag/sequelize-test-helpers/files/3853922/davesag-sq-class-example-1.0.1.tgz.zip)

**Comment by gabrieloczkowski** [comment]
@davesag Thanks for implementing this feature. Great work 👍
