### ISSUE TITLE
facing an issue with checkModelName 

### ISSUE THREAD

**Issue by ikrma47** [davesag/sequelize-test-helpers#243]
### facing an issue with checkModelName 

Hello, when I try to invoke **checkModelName** function with my model as an argument and then invoking it with correct model name the test gets failed with an error _AssertionError: expected undefined to equal '**name-of-my-model**'_

My model file is given as
```javascript
var { BOOLEAN, STRING } = require('sequelize').DataTypes;
var db = require('../config/database');

var ApplicationStatus = db.define('applicationStatus',
  {
    isSubmitted: { type: BOOLEAN, defaultValue: false },
    isAccepted: { type: BOOLEAN, defaultValue: false },
    comments: { type: STRING, allowNull: true },
    isProfile: { type: BOOLEAN, defaultValue: false },
    isCourseCategory: { type: BOOLEAN, defaultValue: false },
    isFirstYear: { type: BOOLEAN, defaultValue: false },
    isSecondYear: { type: BOOLEAN, defaultValue: false },
    isThirdYear: { type: BOOLEAN, defaultValue: false },
    isFinalYear: { type: BOOLEAN, defaultValue: false },
    isGAT: { type: BOOLEAN, defaultValue: false },
    isMS: { type: BOOLEAN, defaultValue: false },
    isExperience: { type: BOOLEAN, defaultValue: false },
    isPreference: { type: BOOLEAN, defaultValue: false },
    isCnicFront: { type: BOOLEAN, defaultValue: false },
    isCnicBack: { type: BOOLEAN, defaultValue: false },
    isMatricCertificate: { type: BOOLEAN, defaultValue: false },
    isIntermediateCertificate: { type: BOOLEAN, defaultValue: false },
    isFirstSemesterDmc: { type: BOOLEAN, defaultValue: false },
    isSecondSemesterDmc: { type: BOOLEAN, defaultValue: false },
    isThirdSemesterDmc: { type: BOOLEAN, defaultValue: false },
    isFourthSemesterDmc: { type: BOOLEAN, defaultValue: false },
    isFifthSemesterDmc: { type: BOOLEAN, defaultValue: false },
    isSixthSemesterDmc: { type: BOOLEAN, defaultValue: false },
    isSeventhSemesterDmc: { type: BOOLEAN, defaultValue: false },
    isEighthSemesterDmc: { type: BOOLEAN, defaultValue: false },
    isBsCertificate: { type: BOOLEAN, defaultValue: false },
    acceptedBy: { type: STRING },
    rejectedBy: { type: STRING },
  },
  { freezeTableName: true, createdAt: true, updatedAt: true });

module.exports = { ApplicationStatus };

```

And My unit test with mocha is given below
```javascript

var {
  checkModelName,
  checkPropertyExists,
} = require('sequelize-test-helpers');
var { ApplicationStatus } = require('../../../models');

describe('#applicationStatus Model', function describing() {
  const applicationStatus = new ApplicationStatus();

  checkModelName(ApplicationStatus)('applicationStatus');

  context('should have properties', function checkingProperties() {
    [
      'isSubmitted',
      'isAccepted',
      'comments',
      'isProfile',
      'isCourseCategory',
      'isFirstYear',
      'isSecondYear',
      'isThirdYear',
      'isFinalYear',
      'isGAT',
      'isMS',
      'isExperience',
      'isPreference',
      'isCnicFront',
      'isCnicBack',
      'isMatricCertificate',
      'isIntermediateCertificate',
      'isFirstSemesterDmc',
      'isSecondSemesterDmc',
      'isThirdSemesterDmc',
      'isFourthSemesterDmc',
      'isFifthSemesterDmc',
      'isSixthSemesterDmc',
      'isSeventhSemesterDmc',
      'isEighthSemesterDmc',
      'isBsCertificate',
      'acceptedBy',
      'rejectedBy',
    ].forEach(checkPropertyExists(applicationStatus));
  });
});
```

the error I am facing is 
```bash
#applicationStatus Model
    1) is named 'applicationStatus'
    should have properties
      √ has property isSubmitted
      √ has property isAccepted
      √ has property comments
      √ has property isProfile
      √ has property isCourseCategory
      √ has property isFirstYear
      √ has property isSecondYear
      √ has property isThirdYear
      √ has property isFinalYear
      √ has property isGAT
      √ has property isMS
      √ has property isExperience
      √ has property isPreference
      √ has property isCnicFront
      √ has property isCnicBack
      √ has property isMatricCertificate
      √ has property isIntermediateCertificate
      √ has property isFirstSemesterDmc
      √ has property isSecondSemesterDmc
      √ has property isThirdSemesterDmc
      √ has property isFourthSemesterDmc
      √ has property isFifthSemesterDmc
      √ has property isSixthSemesterDmc
      √ has property isSeventhSemesterDmc
      √ has property isEighthSemesterDmc
      √ has property isBsCertificate
      √ has property acceptedBy
      √ has property rejectedBy
      
      #applicationStatus Model
       is named 'applicationStatus':
     AssertionError: expected undefined to equal 'applicationStatus'
      at Context.<anonymous> (node_modules\sequelize-test-helpers\src\checks\checkModelName.js:5:32)
      at processImmediate (internal/timers.js:461:21)

```

**Comment by ikrma47** [comment]
@davesag sorry to  bothering you but I am still stuck at this error

**Comment by davesag** [comment]
Your test model needs to use the `sequelize` from `require('sequelize-test-helpers')` not the real `sequelize`.

The usual way to do this is to inject `sequelize` and the `DataTypes` into a model's factory function.

so in your case you'd define your model like

```text
src/models/
  index.js
  ApplicationStatus.js
```

and in `ApplicationStatus.js` you'd define your model like

```js
const model = (sequelize, DataTypes) => {
  const ApplicationStatus = sequelize.define('applicationStatus',
  {
    isSubmitted: { type: DataTypes.BOOLEAN, defaultValue: false },
    // ...etc
  }

  // add any associations

  return ApplicationStatus
}
```

then in your `src/models/index.js` you'd do something like

```js
const path = require('path')
const Sequelize = require('sequelize')
const traverse = require('traverse-folders')
const { configure } = require('sequelize-pg-utilities')

const config = require('config/db_config.json')
const { name, user, password, options } = configure(config)
const sequelize = new Sequelize(name, user, password, options)
const basename = path.basename(module.filename)

const db = {}

const importModel = file => {
  const model = sequelize.import(file)
  db[model.name] = model
}

const associate = modelName => {
  if (typeof db[modelName].associate === 'function') db[modelName].associate(db)
}

traverse(__dirname, importModel, { ignore: basename })

Object.keys(db).forEach(associate)

module.exports = { sequelize, Sequelize, ...db }
```

Then in your test it's easy to import `src/models/ApplicationStatus` directly and inject the mocked `sequelize` and `DataTypes` into it, as per the example in `README.md`.

See the `Import` section in https://sequelize.org/v3/docs/models-definition/

**Comment by ikrma47** [comment]
Thank It helped! and test run successfully but 
When I am associating the model in mocha before( ) it throws error

**Associating**
```javascript
describe("testing models", function testing() {
  var Applicant = ApplicantModel(sequelize, dataTypes)
  var Application = ApplicationModel(sequelize, dataTypes)
  var ApplicantCopy = new Applicant();

  before(function creatingAssociation() {
    Applicant.associate({ Application })
  })
  
  it("applicant model should be associated with 'applications'", () => {
    expect(Applicant.belongsTo).to.have.been.calledWith(Application)
  })
})
```

And the Error I am Facing is

```shell
 1) testing models
       "before all" hook: creatingAssociation for "applicant model should be associated with 'applications'":
     TypeError: Applicant.associate is not a function
      at Context.creatingAssociation (test\index.js:21:15)
      at processImmediate (internal/timers.js:461:21)

```

**Comment by ikrma47** [comment]
Thanks It helped! and test run successfully but 
When I am associating the model in mocha before( ) hook it throws error

**Associating**
```javascript
var sinonChai = require("sinon-chai");
var chai = require('chai')
var{ expect } = require('chai')

chai.use(sinonChai);
var ApplicantModel = require('../models/applicants')
var ApplicationModel = require('../models/applications')
var {
  sequelize,
  dataTypes,
} = require("sequelize-test-helpers")

describe("testing models", function testing() {
  var Applicant = ApplicantModel(sequelize, dataTypes)
  var Application = ApplicationModel(sequelize, dataTypes)

  before(function creatingAssociation() {
    Applicant.associate({ Application })
  })
  
  it("applicant model should be associated with 'applications'", () => {
    expect(Applicant.belongsTo).to.have.been.calledWith(Application)
  })

})
```

And the Error I am Facing is

```shell
 1) testing models
       "before all" hook: creatingAssociation for "applicant model should be associated with 'applications'":
     TypeError: Applicant.associate is not a function
      at Context.creatingAssociation (test\index.js:21:15)
      at processImmediate (internal/timers.js:461:21)

```

**Comment by davesag** [comment]
In your `ApplicantModel` do you define the `associate` function? ala

```js
const model = (sequelize, DataTypes) => {
  const Applicant = sequlize.define('Applicant', { /* schema stuff */ })

  Applicant.associate = ({ Application }) => {
    Applicant.belongsTo(Application)
  }

  return Applicant
}
```

also stop using `var` and use `const` instead.  `var` gets hoisted and can lead to all kinds of hard to debug errors.

**Comment by ikrma47** [comment]
Thanks! My Issues have been resolved

I do not know I was defining my models in a wrong way

```javascript
function model(sequelize, DataTypes) {
  return function ApplicantModel() {
    let Applicant = sequelize.define("applicant", {
      name: { type: DataTypes.STRING },
    }, { tableName: 'applicants' })
    Applicant.associate = function association(models) {
      Applicant.belongsTo(models.Application)
    }
    return Applicant
  }
}

module.exports = model
```

The issue has resolve when I refactored my to 

```javascript
function model(sequelize, DataTypes) {
  let Applicant = sequelize.define("applicant", {
    name: { type: DataTypes.STRING },
  }, { tableName: 'applicants' })
  Applicant.associate = function association(models) {
    Applicant.belongsTo(models.Application)
  }
  return Applicant
}

module.exports = model
```

Anyways thank you so much for the help! 
This testing library make learning easy for the newbies like me.

**Comment by davesag** [comment]
Happy to help.
