### ISSUE TITLE
Error: Invalid Chai property: calledWith

### ISSUE THREAD

**Issue by benniemosher** [davesag/sequelize-test-helpers#30]
Hello,

I was following your blog article, https://itnext.io/unit-testing-sequelize-models-made-easy-108f079f1e38, and was trying to set up a basic `belongsTo` association test. When I copy the code on the tutorial and in this readme I get the bizarre error:

```
1) src/models/FillUp
       associations
         defined a belongsTo association with Car:
     Error: Invalid Chai property: calledWith
      at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:78:17)
      at Context.it (test/models/FillUp.spec.js:42:43)
```

My project and the PR with this code can be found here: https://github.com/benniemosher/fuel/pull/1

Could you please help me figure this one out?

Thanks!

Bennie

**Comment by benniemosher** [comment]
The solution was to steal your `test_helper.js` setup:

```
const chai = require('chai')
const sinonChai = require('sinon-chai')

chai.use(sinonChai)
```

and then to update my `npm test` script to run like:

```
find ./test -name '*spec.js' | NODE_ENV=test xargs mocha --require ./test/test_helper.js
```

This is solved. Closing.
